### ISSUE TITLE
Load Fail

### ISSUE THREAD

**Issue by flysiunb** [valthrunner/Valthrun#4]
KDMapper prompts Failed to register and start service for the volatile driver
![666](https://github.com/valthrunner/Valthrun/assets/140980081/4de75c6a-4526-4df4-a9a9-1e78ea461aac)

**Comment by valthrunner** [comment]
@flysiunb Hey, seems like you have something like faceit running. Hope you already found a solution on the discord.
If not look on there https://discord.com/invite/ecKbpAPW5T, nearly every issue that can occur was already discussed and probably solved on there.
