### ISSUE TITLE
Missing kernel drivers

### ISSUE THREAD

**Issue by maciupikciuxd** [valthrunner/Valthrun#6]
yeah so i am trying to set everything up but each file has its own trouble

run file says:'C:\Users\myname\AppData\Local\Temp/valth.bat' is not recognized as an internal or external command,
operable program or batch file.

it just can't find the file so its not downloaded(idk where to find it)

kdmapper when opened just closes(lets just skip the part that it is considered as a virus)

valthrun-driver.sys cannot be opened bc there is no app to do this

and controller app says: Could not find the kernel driver interface.
Ensure you have successfully loaded/mapped the kernel driver (valthrun-driver.sys) before starting the CS2 controller.

sry for my long issue but i am a newbie and have no clue how this should be done :)

**Comment by valthrunner** [comment]
Hey @maciupikciuxd, I would like to help you please give me your discord tag and I will add you and we will see if we can find a solution!

**Comment by maciupikciuxd** [comment]
works now, thanks for help on dc already


pt., 15 mar 2024 o 10:40 Valthrunner ***@***.***> napisał(a):
