### ISSUE TITLE
New driver architecture and download URL

### ISSUE THREAD

**Issue by WolverinDEV** [valthrunner/Valthrun#7]
Hey ho,  
with Valthrun 0.5.0 the way Valthrun is structured has changed.  
Additionally did we transition into self hosting the artifacts and will shift away from github releases.  
  
But no worries, there is a new API providing all required information for continuing to automatically download all resources.  
Here is a quick overview: 
- GET `https://valth.run/download/[bundle-name]/info`  
Retrieve information about contents of the download bundles offered at https://valth.run/download.  
`versionHash` can be used to determine if the contents have been change or not.  
- GET `https://valth.run/api/artifacts`  
Get a list of all individually available artifacts which are offered (more fine grained control over which files and version will be downloaded).
- GET `https://valth.run/api/artifacts/[artifact id or slug]`
Get a list of available tracks for the artifact
- GET `https://valth.run/api/artifacts/[artifact id or slug]/[track id or slug]`
Get a list of available versions for that track of the artifact
- GET `https://valth.run/api/artifacts/[artifact id or slug]/[track id or slug]/[version id]`
Get information about the specific version of that artifact.  
Note: The information do not differ from the version entry in the version list of a track.
- GET `https://valth.run/api/artifacts/[artifact id or slug]/[track id or slug]/[version id]/download`
Download that specific version

When it comes to the new architecture you can read everything here:  
https://wiki.valth.run/getting-started/architechture
  
Note:  
The new Zenith driver concerns are currently outside the scope of this work.   
In the future, integrating it could be beneficial, but doing so will require a completely different workflow.  
  
PS: I may suggest that you switch to use powershell instead of just a regular .bat file as it might be more handy with the tools available :)

**Comment by valthrunner** [comment]
Thanks!
