### ISSUE TITLE
When the overlay is started my whole screen gets coverd in a black window

### ISSUE THREAD

**Issue by Johntex123** [valthrunner/Valthrun#8]
**Describe the bug IN DETAIL**
I ran the run.bat it started cs2 and started the overlay but the overlay just covered my entire screen in a black window

**Screenshots**
can't take a screenshot cuz the window goes away when i do win + shift + s

**Windows:**
 - OS version: Windows 10 Pro 22H2

**Dicord:**
So I can ping/message you about the issue if needed! If you dont include your discord this issue will be closed.
 - Name: johntex187_ or Johntex187 idk cuz im dumb

**Additional context**

**Comment by valthrunner** [comment]
https://wiki.valth.run/troubleshooting/overlay/amd_opengl
